# Generated by Django 4.1.4 on 2023-01-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('seller', 'seller'), ('buyer', 'buyer'), ('deliver', 'deliver')], max_length=10),
        ),
    ]
