# Generated by Django 4.1.4 on 2022-12-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('buyer', 'buyer'), ('seller', 'seller')], max_length=6),
        ),
    ]
