# Generated by Django 4.1.4 on 2023-01-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='rating',
            field=models.CharField(blank=True, choices=[('4', '4'), ('5', '5'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('on_the_way', 'On The Way'), ('stolen', 'Stolen'), ('paid', 'Paid')], max_length=20),
        ),
    ]
