# Generated by Django 4.1.4 on 2023-01-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_cart_rating_cart_review_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', '1'), ('3', '3'), ('2', '2'), ('4', '4'), ('5', '5')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('stolen', 'Stolen'), ('on_the_way', 'On The Way'), ('paid', 'Paid'), ('pending', 'Pending')], max_length=20),
        ),
    ]
