# Generated by Django 4.1.4 on 2023-01-08 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0020_alter_cart_rating_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliver_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='rating',
            field=models.CharField(blank=True, choices=[('3', '3'), ('5', '5'), ('2', '2'), ('1', '1'), ('4', '4')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('on_the_way', 'On The Way'), ('delivered', 'Delivered'), ('stolen', 'Stolen'), ('paid', 'Paid')], max_length=20),
        ),
    ]
