# Generated by Django 4.1.4 on 2023-01-08 18:32

from django.db import migrations, models
import utils.misc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.misc.image_path_category),
        ),
    ]
